[2023-10-08 12:05:05,006] ERROR _log() L96   Error on request:
Traceback (most recent call last):
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/cli.py", line 907, in app
    raise err from None
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/cli.py", line 898, in run_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/cli.py", line 313, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/home/phcosta/Documents/ticket/api/app.py", line 58, in <module>
    @app.get('/analista', tags=[analista_tag],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask_openapi3/scaffold.py", line 214, in decorator
    self.add_url_rule(rule, view_func=view_func, **options)
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/scaffold.py", line 50, in wrapper_func
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/app.py", line 1059, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: get_analista - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:05:26,093] INFO _log() L96    * Detected change in '/home/phcosta/Documents/ticket/api/app.py', reloading - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:05:27,245] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:05:27] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:05:27,264] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:05:27] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:05:27,265] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:05:27] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:05:27,266] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:05:27] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:05:27,371] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:05:27] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:05:40,699] INFO _log() L96    * Detected change in '/home/phcosta/Documents/ticket/api/app.py', reloading - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:06:07,303] INFO _log() L96    * Detected change in '/home/phcosta/Documents/ticket/api/route/analista/analista.py', reloading - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:06:22,868] INFO _log() L96    * Detected change in '/home/phcosta/Documents/ticket/api/route/analista/analista.py', reloading - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:07:39,600] INFO _log() L96    * Detected change in '/home/phcosta/Documents/ticket/api/route/analista/processo.py', reloading - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:07:51,191] INFO _log() L96    * Detected change in '/home/phcosta/Documents/ticket/api/app.py', reloading - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:07:53,870] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:07:53] "[35m[1mGET /openapi/swagger HTTP/1.1[0m" 500 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:07:53,874] ERROR _log() L96   Error on request:
Traceback (most recent call last):
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/cli.py", line 907, in app
    raise err from None
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/cli.py", line 898, in run_command
    app = info.load_app()
          ^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/cli.py", line 313, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/cli.py", line 219, in locate_app
    __import__(module_name)
  File "/home/phcosta/Documents/ticket/api/app.py", line 169, in <module>
    @app.get('/processos', tags=[processo_tag],
                                 ^^^^^^^^^^^^^^
NameError: name 'processo_tag' is not defined - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:01,752] INFO _log() L96    * Detected change in '/home/phcosta/Documents/ticket/api/app.py', reloading - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:04,719] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:08:04] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:04,739] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:08:04] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:04,739] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:08:04] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:04,742] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:08:04] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:04,841] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:08:04] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:14,659] DEBUG add_processo() L227  Adicionando o processo 'Nota Fiscal na base de dados - call_trace=/home/phcosta/Documents/ticket/api/app.py L227 
[2023-10-08 12:08:14,670] DEBUG add_processo() L235  Nota Fiscal adicionado com sucesso. - call_trace=/home/phcosta/Documents/ticket/api/app.py L235 
[2023-10-08 12:08:14,671] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:08:14] "POST /processo HTTP/1.1" 200 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:22,572] DEBUG get_processos() L176  Coletando Processos - call_trace=/home/phcosta/Documents/ticket/api/app.py L176 
[2023-10-08 12:08:22,581] DEBUG get_processos() L186  1 Processos encontrados - call_trace=/home/phcosta/Documents/ticket/api/app.py L186 
[2023-10-08 12:08:22,581] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:08:22] "GET /processos HTTP/1.1" 200 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:41,401] INFO _log() L96    * Detected change in '/home/phcosta/Documents/ticket/api/app.py', reloading - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:44,557] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:08:44] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:44,574] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:08:44] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
