[2023-10-08 11:58:53,945] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 11:58:56,048] ERROR log_exception() L1414 Exception on /analistas [GET] - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/app.py L1414
Traceback (most recent call last):
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask_openapi3/scaffold.py", line 127, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/route/analista/analista.py", line 19, in get_analistas
    logger.debug(f"Coletando Analistas")
    ^^^^^^
NameError: name 'logger' is not defined
[2023-10-08 11:58:56,049] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 11:58:56] "[35m[1mGET /analistas HTTP/1.1[0m" 500 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 11:59:20,459] INFO _log() L96    * Detected change in '/home/phcosta/Documents/ticket/api/route/analista/analista.py', reloading - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 11:59:20,573] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 11:59:21,815] DEBUG get_analistas() L20   Coletando Analistas - call_trace=/home/phcosta/Documents/ticket/api/route/analista/analista.py L20  
[2023-10-08 11:59:21,815] ERROR log_exception() L1414 Exception on /analistas [GET] - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/app.py L1414
Traceback (most recent call last):
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/flask_openapi3/scaffold.py", line 127, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/phcosta/Documents/ticket/api/route/analista/analista.py", line 22, in get_analistas
    session = Session()
              ^^^^^^^
NameError: name 'Session' is not defined
[2023-10-08 11:59:21,816] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 11:59:21] "[35m[1mGET /analistas HTTP/1.1[0m" 500 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 11:59:38,050] INFO _log() L96    * Detected change in '/home/phcosta/Documents/ticket/api/route/analista/analista.py', reloading - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 11:59:38,157] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 11:59:39,637] DEBUG get_analistas() L21   Coletando Analistas - call_trace=/home/phcosta/Documents/ticket/api/route/analista/analista.py L21  
[2023-10-08 11:59:39,644] DEBUG get_analistas() L31   1 Analistas encontrados - call_trace=/home/phcosta/Documents/ticket/api/route/analista/analista.py L31  
[2023-10-08 11:59:39,644] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 11:59:39] "GET /analistas HTTP/1.1" 200 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 11:59:59,684] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 11:59:59] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 11:59:59,703] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 11:59:59] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 11:59:59,703] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 11:59:59] "GET /openapi/static/css/swagger-ui.css HTTP/1.1" 200 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 11:59:59,704] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 11:59:59] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 11:59:59,805] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 11:59:59] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:00:04,922] DEBUG get_analistas() L21   Coletando Analistas - call_trace=/home/phcosta/Documents/ticket/api/route/analista/analista.py L21  
[2023-10-08 12:00:04,923] DEBUG get_analistas() L31   1 Analistas encontrados - call_trace=/home/phcosta/Documents/ticket/api/route/analista/analista.py L31  
[2023-10-08 12:00:04,924] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:00:04] "GET /analistas HTTP/1.1" 200 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:04:59,455] INFO _log() L96    * Detected change in '/home/phcosta/Documents/ticket/api/route/analista/analista.py', reloading - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:04:59,560] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:05:04,988] INFO _log() L96   192.168.0.15 - - [08/Oct/2023 12:05:04] "[35m[1mGET /openapi/swagger HTTP/1.1[0m" 500 - - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:05:26,210] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:05:40,795] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:06:07,403] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:06:22,970] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:07:39,714] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:07:51,301] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:01,853] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:08:41,502] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:09:22,185] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2023-10-08 12:10:16,866] INFO _log() L96    * Restarting with stat - call_trace=/home/phcosta/Documents/ticket/api/venv/lib/python3.11/site-packages/werkzeug/_internal.py L96  
